// "use client"
import './globals.css'
import { Inter } from 'next/font/google'
import connectDB from './utils/dbconnect'
import NavbarUnique from './Navbar/page'
// import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blessed Pakistan',
  description: 'Generated by create next app',
}

export default  function RootLayout({ children }) { 
 connectDB()
//  const pathName = usePathname();
//  console.log(pathName) 
 return (
    <html lang="en">
   {/* {pathName !== '/' && pathName !== '/Dashboard' ? 
   <>
   <NavbarUnique />
   </>
   : null
     } */}
      <body className={inter.className}>{children}</body>
    </html>
  )
}
